{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\nUnit\\test_pytest.py:15: AssertionError"}, "start": 1607338044874, "stop": 1607338044874, "uuid": "d84f41b6-dc35-4360-9261-fed351822ff9", "historyId": "a5e209af95590db3e8d23ad0d2aa46d6", "testCaseId": "a57266e7f2e6fb6b80151f9d4aba9a00", "fullName": "Unit.test_pytest#test_answer", "labels": [{"name": "parentSuite", "value": "Unit"}, {"name": "suite", "value": "test_pytest"}, {"name": "host", "value": "P80230531"}, {"name": "thread", "value": "17456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Unit.test_pytest"}]}