{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'llo')", "trace": "def test_two():\n        print(\"正在执行----test_two\")\n        x = \"hello\"\n>       assert hasattr(x, 'llo')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'llo')\n\nUnit\\test_fixture.py:41: AssertionError"}, "attachments": [{"name": "stdout", "source": "ca1974b2-db99-4065-9c7e-819db5d51dd5-attachment.txt", "type": "text/plain"}], "start": 1607484686597, "stop": 1607484686597, "uuid": "bda3fc41-bd15-49b3-9d8f-130072900281", "historyId": "e490c4d08f0e2f14de82b3c1ff26dcb4", "testCaseId": "e979e68f19fc6a2bdd1945bbc97be23d", "fullName": "Unit.test_fixture#test_two", "labels": [{"name": "parentSuite", "value": "Unit"}, {"name": "suite", "value": "test_fixture"}, {"name": "host", "value": "P80230531"}, {"name": "thread", "value": "10040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Unit.test_fixture"}]}