{"name": "test_four", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <Unit.test_fixture.TestCase object at 0x000001B1949D4208>\n\n    def test_four(self):\n        print(\"正在执行----test_four\")\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\nUnit\\test_fixture.py:66: AssertionError"}, "attachments": [{"name": "stdout", "source": "266f460d-8622-4e7c-9f49-ba0e6f441960-attachment.txt", "type": "text/plain"}], "start": 1607338044864, "stop": 1607338044865, "uuid": "57dffea3-22d6-4f08-82a4-2e116b286481", "historyId": "e70f8fa5b69bd98e1c40ffda4b040e94", "testCaseId": "3cc79c931a15eab8e561d4b897108fd9", "fullName": "Unit.test_fixture.TestCase#test_four", "labels": [{"name": "parentSuite", "value": "Unit"}, {"name": "suite", "value": "test_fixture"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "P80230531"}, {"name": "thread", "value": "17456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Unit.test_fixture"}]}