{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'llo')", "trace": "def test_two():\n        print(\"正在执行----test_two\")\n        x = \"hello\"\n>       assert hasattr(x, 'llo')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'llo')\n\nUnit\\test_fixture.py:41: AssertionError"}, "attachments": [{"name": "stdout", "source": "2fa5a9c4-4a4b-411d-bf73-05670cc99278-attachment.txt", "type": "text/plain"}], "start": 1607338044851, "stop": 1607338044852, "uuid": "9e8a4ddd-0e1a-49db-b5ac-61aaaebd574b", "historyId": "e490c4d08f0e2f14de82b3c1ff26dcb4", "testCaseId": "e979e68f19fc6a2bdd1945bbc97be23d", "fullName": "Unit.test_fixture#test_two", "labels": [{"name": "parentSuite", "value": "Unit"}, {"name": "suite", "value": "test_fixture"}, {"name": "host", "value": "P80230531"}, {"name": "thread", "value": "17456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Unit.test_fixture"}]}