{"name": "test_four", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <Unit.test_fixture.TestCase object at 0x0000022151B0A308>\n\n    def test_four(self):\n        print(\"正在执行----test_four\")\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\nUnit\\test_fixture.py:66: AssertionError"}, "attachments": [{"name": "stdout", "source": "5e46dcc2-468f-479c-a5a5-7c0ac5869631-attachment.txt", "type": "text/plain"}], "start": 1607484686610, "stop": 1607484686610, "uuid": "c715769b-619e-4f2a-b197-a4704a5d9dd5", "historyId": "e70f8fa5b69bd98e1c40ffda4b040e94", "testCaseId": "3cc79c931a15eab8e561d4b897108fd9", "fullName": "Unit.test_fixture.TestCase#test_four", "labels": [{"name": "parentSuite", "value": "Unit"}, {"name": "suite", "value": "test_fixture"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "P80230531"}, {"name": "thread", "value": "10040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Unit.test_fixture"}]}